#pragma once

#define DVI_CLK_P ADAFRUIT_FRUIT_JAM_DVI_CKP_PIN
#define DVI_D0_P  ADAFRUIT_FRUIT_JAM_DVI_D0P_PIN
#define DVI_D1_P  ADAFRUIT_FRUIT_JAM_DVI_D1P_PIN
#define DVI_D2_P  ADAFRUIT_FRUIT_JAM_DVI_D2P_PIN

// native
#define SD_CLK   ADAFRUIT_FRUIT_JAM_SDIO_CLOCK_PIN
#define SD_CMD   ADAFRUIT_FRUIT_JAM_SDIO_COMMAND_PIN
#define SD_DAT0  ADAFRUIT_FRUIT_JAM_SDIO_DATA0_PIN

// spi
#define SD_SCK   ADAFRUIT_FRUIT_JAM_SD_SCK_PIN
#define SD_MOSI  ADAFRUIT_FRUIT_JAM_SD_MOSI_PIN
#define SD_MISO  ADAFRUIT_FRUIT_JAM_SD_MISO_PIN
#define SD_CS    ADAFRUIT_FRUIT_JAM_SD_CS_PIN
