name: Visual Studio (.sln)
on:
  push:
    branches:
      - '**' # only run on branches
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install deps
      shell: bash
      run: |
        ci/install_sdl_vs.sh
        python -m pip install 32blit

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      run: msbuild.exe vs/32blit.sln
